---
deployment:
  tasks:
    - export DEPLOYPATH=/home/okgyhuxe/public_html/zenesz-fe
    - /bin/rm -r $DEPLOYPATH/static/*
    - /bin/cp -R build/static $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp build/asset-manifest.json $DEPLOYPATH
    - /bin/cp build/favicon.ico $DEPLOYPATH
    - /bin/cp build/index.html $DEPLOYPATH